import type {
  FilterChipDef,
  Product,
  ProductCategory,
  ProductCategoryKey,
  SystemStep,
  SystemStepConnector,
} from "./types";

/** Ordered by dependency chain: each step requires the one before it. */
export const SYSTEM_STEPS: SystemStep[] = [
  {
    key: "solar-panels",
    label: "Solar Panels",
    iconSrc: "/images/products/header/layer-solar-panel-icon.png",
  },
  {
    key: "inverter",
    label: "Inverter",
    iconSrc: "/images/products/header/layer-inverter-icon.png",
  },
  {
    key: "batteries",
    label: "Batteries",
    iconSrc: "/images/products/header/layer-battery-icon.png",
  },
  {
    key: "ev-charger",
    label: "EV Charger",
    iconSrc: "/images/products/header/layer-ev-charger-icon.png",
  },
];

/** Default step to treat as "current" when the active category isn't one of the four steps above. */
export const DEFAULT_SYSTEM_STEP_KEY = "batteries";

export const SYSTEM_STEP_CONNECTORS: SystemStepConnector[] = [
  "requires",
  "requires",
  "dotted",
];

/** Step keys are diagram-flow labels ("Inverter"), category keys are plural catalog slugs. */
export const SYSTEM_STEP_CATEGORY: Record<string, ProductCategoryKey> = {
  "solar-panels": "solar-panels",
  inverter: "inverters",
  batteries: "batteries",
  "ev-charger": "ev-chargers",
};

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  {
    key: "batteries",
    label: "Batteries",
    iconSrc: "/images/products/header/layer-battery-icon.png",
    count: 842,
  },
  {
    key: "solar-panels",
    label: "Solar Panels",
    iconSrc: "/images/products/header/layer-solar-panel-icon.png",
    count: 1120,
  },
  {
    key: "inverters",
    label: "Inverters",
    iconSrc: "/images/products/header/layer-inverter-icon.png",
    count: 610,
  },
  {
    key: "ev-chargers",
    label: "EV Chargers",
    iconSrc: "/images/products/header/layer-ev-charger-icon.png",
    count: 240,
  },
  {
    key: "heat-pumps",
    label: "Heat Pumps",
    iconSrc: "/images/products/header/layer-heat-pump-icon.png",
    count: 188,
  },
];

export const FILTERS_BY_CATEGORY: Record<ProductCategoryKey, FilterChipDef[]> = {
  batteries: [
    { key: "all", label: "All batteries", kind: "all" },
    { key: "residential", label: "Residential", kind: "segment", segment: "residential" },
    { key: "commercial", label: "Commercial", kind: "segment", segment: "commercial" },
    { key: "under-10", label: "Under 10kWh", kind: "band", max: 10 },
    { key: "10-20", label: "10-20kWh", kind: "band", min: 10, max: 20 },
    { key: "20-plus", label: "20kWh+", kind: "band", min: 20 },
  ],
  "solar-panels": [
    { key: "all", label: "All solar panels", kind: "all" },
    { key: "residential", label: "Residential", kind: "segment", segment: "residential" },
    { key: "commercial", label: "Commercial", kind: "segment", segment: "commercial" },
    { key: "under-400", label: "Under 400W", kind: "band", max: 400 },
    { key: "400-500", label: "400-500W", kind: "band", min: 400, max: 500 },
    { key: "500-plus", label: "500W+", kind: "band", min: 500 },
  ],
  inverters: [
    { key: "all", label: "All inverters", kind: "all" },
    { key: "residential", label: "Residential", kind: "segment", segment: "residential" },
    { key: "commercial", label: "Commercial", kind: "segment", segment: "commercial" },
    { key: "under-5", label: "Under 5kW", kind: "band", max: 5 },
    { key: "5-10", label: "5-10kW", kind: "band", min: 5, max: 10 },
    { key: "10-plus", label: "10kW+", kind: "band", min: 10 },
  ],
  "ev-chargers": [
    { key: "all", label: "All EV chargers", kind: "all" },
    { key: "residential", label: "Residential", kind: "segment", segment: "residential" },
    { key: "commercial", label: "Commercial", kind: "segment", segment: "commercial" },
    { key: "under-7", label: "Under 7kW", kind: "band", max: 7 },
    { key: "7-22", label: "7-22kW", kind: "band", min: 7, max: 22 },
    { key: "22-plus", label: "22kW+", kind: "band", min: 22 },
  ],
  "heat-pumps": [
    { key: "all", label: "All heat pumps", kind: "all" },
    { key: "residential", label: "Residential", kind: "segment", segment: "residential" },
    { key: "commercial", label: "Commercial", kind: "segment", segment: "commercial" },
    { key: "under-5", label: "Under 5kW", kind: "band", max: 5 },
    { key: "5-10", label: "5-10kW", kind: "band", min: 5, max: 10 },
    { key: "10-plus", label: "10kW+", kind: "band", min: 10 },
  ],
};

export const PRODUCTS_BY_CATEGORY: Record<ProductCategoryKey, Product[]> = {
  batteries: [
    {
      id: "bluetti-ep2000-stack",
      categoryKey: "batteries",
      segment: "residential",
      specValue: 21.3,
      badge: "Best Seller",
      brand: "Bluetti",
      name: "EP2000 21.3kWh Stack",
      model: "EP2000-HV800-B700x2/24",
      rating: 4.9,
      hasDatasheet: true,
      inStock: true,
      features: ["10yr warranty", "Modular expansion", "Whole-home backup"],
      price: 15990,
      photo: {
        background: "/images/products/bluetti-lifestyle.jpg",
        image: "/images/products/bluetti-stack.png",
      },
    },
    {
      id: "foxess-eq4880",
      categoryKey: "batteries",
      segment: "residential",
      specValue: 14.64,
      badge: "Popular",
      brand: "FoxESS",
      name: "EQ4880 14.64kWh",
      model: "EQ4880-HV-S/2024",
      rating: 4.8,
      hasDatasheet: true,
      inStock: true,
      features: ["10yr warranty", "Install included", "Backup-ready"],
      price: 6991,
    },
    {
      id: "sigenergy-18kwh",
      categoryKey: "batteries",
      segment: "residential",
      specValue: 18,
      brand: "Sigenergy",
      name: "SigenStor 18kWh",
      model: "SIGEN-18-HV/2024",
      rating: 4.9,
      hasDatasheet: true,
      inStock: true,
      features: ["DC fast-charge", "12kW controller"],
      price: 11110,
      compareInitially: true,
    },
    {
      id: "tesla-powerwall-3",
      categoryKey: "batteries",
      segment: "residential",
      specValue: 13.5,
      badge: "Best Value",
      brand: "Tesla",
      name: "Powerwall 3 13.5kWh",
      model: "PW3-AC-1707000-XX/23",
      rating: 4.9,
      hasDatasheet: true,
      inStock: true,
      features: ["10yr warranty", "Built-in inverter", "App monitoring"],
      price: 9990,
    },
    {
      id: "byd-battery-box-hvs",
      categoryKey: "batteries",
      segment: "residential",
      specValue: 10.24,
      brand: "BYD",
      name: "Battery-Box Premium HVS",
      model: "HVS-10.24/22",
      rating: 4.7,
      hasDatasheet: true,
      inStock: true,
      features: ["10yr warranty", "Modular expansion"],
      price: 7450,
    },
    {
      id: "alpha-ess-smile5",
      categoryKey: "batteries",
      segment: "commercial",
      specValue: 21.2,
      brand: "Alpha ESS",
      name: "SMILE5 21.2kWh",
      model: "SMILE5-21.2-3P/24",
      rating: 4.6,
      hasDatasheet: true,
      inStock: true,
      features: ["10yr warranty", "Three-phase ready", "Backup-ready"],
      price: 13290,
    },
    {
      id: "growatt-aro-hv",
      categoryKey: "batteries",
      segment: "commercial",
      specValue: 30.72,
      brand: "Growatt",
      name: "ARO HV 30.72kWh",
      model: "ARO-30.72-HV/24",
      rating: 4.5,
      hasDatasheet: true,
      inStock: false,
      features: ["10yr warranty", "Commercial-grade", "Backup-ready"],
      price: 17850,
    },
  ],
  "solar-panels": [
    {
      id: "jinko-tiger-neo-440",
      categoryKey: "solar-panels",
      segment: "residential",
      specValue: 440,
      badge: "Popular",
      brand: "Jinko Solar",
      name: "Tiger Neo 440W",
      model: "JKM440N-54HL4-B/24",
      rating: 4.8,
      hasDatasheet: true,
      inStock: true,
      features: ["25yr warranty", "N-type cell", "Install included"],
      price: 349,
    },
    {
      id: "trina-vertex-500",
      categoryKey: "solar-panels",
      segment: "residential",
      specValue: 500,
      badge: "Best Seller",
      brand: "Trina Solar",
      name: "MaxPower 500",
      model: "RIS-RSM144-9-595BNDG/30/21",
      rating: 4.9,
      hasDatasheet: true,
      inStock: true,
      features: ["Bifacial Gain", "Commercial Grade", "Heavy Duty Glass"],
      price: 399,
    },
    {
      id: "rec-alpha-pure-430",
      categoryKey: "solar-panels",
      segment: "residential",
      specValue: 430,
      badge: "Best Value",
      brand: "REC Group",
      name: "Alpha Pure-R 430W",
      model: "REC430AA-PURE-R/24",
      rating: 4.8,
      hasDatasheet: true,
      inStock: true,
      features: ["25yr warranty", "Lead-free", "All-black design"],
      price: 379,
    },
    {
      id: "longi-hi-mo6-580",
      categoryKey: "solar-panels",
      segment: "commercial",
      specValue: 580,
      brand: "LONGi",
      name: "Hi-MO 6 580W",
      model: "LR7-72HGD-580M/24",
      rating: 4.6,
      hasDatasheet: true,
      inStock: true,
      features: ["25yr warranty", "Commercial-grade"],
      price: 449,
    },
  ],
  inverters: [
    {
      id: "fronius-primo-5",
      categoryKey: "inverters",
      segment: "residential",
      specValue: 5,
      badge: "Popular",
      brand: "Fronius",
      name: "Primo GEN24 5.0kW",
      model: "GEN24-5.0-PLUS/24",
      rating: 4.7,
      hasDatasheet: true,
      inStock: true,
      features: ["10yr warranty", "Install included", "Backup-ready"],
      price: 2190,
    },
    {
      id: "solaredge-se7600h",
      categoryKey: "inverters",
      segment: "residential",
      specValue: 7.6,
      brand: "SolarEdge",
      name: "SE7600H HD-Wave",
      model: "SE7600H-AUS/23",
      rating: 4.8,
      hasDatasheet: true,
      inStock: true,
      features: ["12yr warranty", "Module-level optimisation"],
      price: 2650,
    },
    {
      id: "sungrow-sh10rt",
      categoryKey: "inverters",
      segment: "residential",
      specValue: 10,
      badge: "Best Value",
      brand: "Sungrow",
      name: "SH10RT Hybrid",
      model: "SH10RT-3P/24",
      rating: 4.7,
      hasDatasheet: true,
      inStock: true,
      features: ["10yr warranty", "Three-phase", "Battery-ready"],
      price: 3190,
    },
    {
      id: "sma-sunny-tripower-25",
      categoryKey: "inverters",
      segment: "commercial",
      specValue: 25,
      brand: "SMA",
      name: "Sunny Tripower 25kW",
      model: "STP25000TL-30/24",
      rating: 4.6,
      hasDatasheet: true,
      inStock: false,
      features: ["10yr warranty", "Commercial-grade", "Three-phase"],
      price: 6890,
    },
  ],
  "ev-chargers": [
    {
      id: "tesla-wall-connector",
      categoryKey: "ev-chargers",
      segment: "residential",
      specValue: 11,
      badge: "Popular",
      brand: "Tesla",
      name: "Wall Connector Gen 3",
      model: "WC3-AUS-11KW/23",
      rating: 4.8,
      hasDatasheet: true,
      inStock: true,
      features: ["4yr warranty", "Wi-Fi enabled", "Install included"],
      price: 990,
    },
    {
      id: "zappi-v2",
      categoryKey: "ev-chargers",
      segment: "residential",
      specValue: 7,
      brand: "myenergi",
      name: "Zappi V2 7kW",
      model: "ZAPPI-V2-7-AUS/23",
      rating: 4.7,
      hasDatasheet: true,
      inStock: true,
      features: ["3yr warranty", "Solar-matching charge"],
      price: 1290,
    },
    {
      id: "wallbox-pulsar-plus",
      categoryKey: "ev-chargers",
      segment: "residential",
      specValue: 7.4,
      badge: "Best Value",
      brand: "Wallbox",
      name: "Pulsar Plus 7.4kW",
      model: "PLP1-0-2-4-9-002-A/24",
      rating: 4.6,
      hasDatasheet: true,
      inStock: true,
      features: ["3yr warranty", "App control"],
      price: 890,
    },
    {
      id: "delta-ac-max-22",
      categoryKey: "ev-chargers",
      segment: "commercial",
      specValue: 22,
      brand: "Delta",
      name: "AC Max 22kW",
      model: "AC-MAX-22-3P/24",
      rating: 4.5,
      hasDatasheet: true,
      inStock: true,
      features: ["3yr warranty", "Commercial-grade", "Three-phase"],
      price: 2190,
    },
  ],
  "heat-pumps": [
    {
      id: "sanden-eco-plus",
      categoryKey: "heat-pumps",
      segment: "residential",
      specValue: 2.6,
      badge: "Popular",
      brand: "Sanden",
      name: "Eco Plus 315L",
      model: "GAU-315EQTAS/23",
      rating: 4.8,
      hasDatasheet: true,
      inStock: true,
      features: ["10yr warranty", "Solar-matching", "Install included"],
      price: 4290,
    },
    {
      id: "reclaim-energy-gen3",
      categoryKey: "heat-pumps",
      segment: "residential",
      specValue: 3.1,
      brand: "Reclaim Energy",
      name: "Gen3 270L",
      model: "RE-G3-270/24",
      rating: 4.6,
      hasDatasheet: true,
      inStock: true,
      features: ["7yr warranty", "CO2 refrigerant"],
      price: 3690,
    },
    {
      id: "midea-eco-master",
      categoryKey: "heat-pumps",
      segment: "residential",
      specValue: 4.5,
      badge: "Best Value",
      brand: "Midea",
      name: "Eco Master 400L",
      model: "RSJ-40/V1-E/24",
      rating: 4.5,
      hasDatasheet: true,
      inStock: true,
      features: ["5yr warranty", "Quiet operation"],
      price: 3190,
    },
    {
      id: "evoheat-commercial",
      categoryKey: "heat-pumps",
      segment: "commercial",
      specValue: 12,
      brand: "Evoheat",
      name: "Fusion 5T Commercial",
      model: "FUSION-5T-3P/24",
      rating: 4.4,
      hasDatasheet: true,
      inStock: false,
      features: ["7yr warranty", "Commercial-grade", "Three-phase"],
      price: 8990,
    },
  ],
};

export const SPEC_LABEL_BY_CATEGORY: Record<ProductCategoryKey, string> = {
  batteries: "Capacity",
  "solar-panels": "Power",
  inverters: "Rated Power",
  "ev-chargers": "Charge Rate",
  "heat-pumps": "Heating Capacity",
};

export const SPEC_UNIT_BY_CATEGORY: Record<ProductCategoryKey, string> = {
  batteries: "kWh",
  "solar-panels": "W",
  inverters: "kW",
  "ev-chargers": "kW",
  "heat-pumps": "kW",
};

export const BAND_GROUP_LABEL: Record<ProductCategoryKey, string> = {
  batteries: "Capacity Range",
  "solar-panels": "Wattage Range",
  inverters: "Power Range",
  "ev-chargers": "Charge Rate",
  "heat-pumps": "Capacity Range",
};

export const MAX_COMPARE_PRODUCTS = 3;

export const ALL_PRODUCTS: Product[] = Object.values(PRODUCTS_BY_CATEGORY).flat();

export const PRODUCT_BY_ID: Record<string, Product> = Object.fromEntries(
  ALL_PRODUCTS.map((product) => [product.id, product]),
);
